3-module
js-tasks-ru/jsbasic-20241021_vctorsenin pull request #3
Opened 2024-11-11 12:22 UTC by Vitek-123

2024-11-11 12:23 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-11-11 18:27 UTC, SinimaWath requested changes

2024-11-11 18:27 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  }
Давай тут используем метод `map`

2024-11-11 18:27 UTC, SinimaWath commented on 3-module/2-task/index.js
> +    }));
Давай тут используем метод `filter`

2024-11-11 18:27 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  nam = nam.join("\n");
Давай тут используем методы `filter->map->join('\n')`

2024-11-11 18:27 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  });
Тут вместо forEach давай используем: `map`

2024-11-15 08:12 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-11-15 08:15 UTC, closed without merging